from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354ef854b2cf'
down_revision = 'd83cf4b9c175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        # Adjust the constraint name based on what you find in the DB
        # batch_op.drop_constraint('actual_constraint_name', type_='foreignkey')  # Replace with actual name
        # Or remove the drop constraint line if there's no constraint to drop
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), nullable=False))
        # Adjust the constraint if needed
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'])

    # ### end Alembic commands ###
